---

- name: Include version-specific variables for Ubuntu.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for Debian.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution == 'Debian'
- name: Include version-specific variables for RedHat
  ansible.builtin.include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- name: Set fact is_container
  ansible.builtin.set_fact:
    is_container: true
  when: >
    (ansible_virtualization_type is defined and
      (ansible_virtualization_type == "docker"
       or ansible_virtualization_type == "containerd"
       or ansible_virtualization_type == "container"
      )
    )

- name: Import spiderfoot
  ansible.builtin.import_tasks: spiderfoot.yml

- name: Import firewall-ufw
  ansible.builtin.import_tasks: firewall-ufw.yml
  when:
    - not is_container | bool

- name: Import systemd
  ansible.builtin.import_tasks: systemd.yml

- name: Import restore
  ansible.builtin.import_tasks: restore.yml
  when:
    - spiderfoot_db_restore | bool
