---

- name: Debian | Update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: RedHat | Update cache
  ansible.builtin.package:
    update_cache: true
  when: ansible_os_family == 'RedHat'

- name: Ensure dependencies packages are present
  ansible.builtin.package:
    name:
      - git
      - python3
      - python3-pip
      - python3-virtualenv
      - sqlite3
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Ensure spiderfoot user exists
  ansible.builtin.user:
    name: "{{ spiderfoot_user }}"
    home: "{{ spiderfoot_home }}"
    system: true

- name: Git clone spiderfoot
  ansible.builtin.git:
    repo: https://github.com/smicallef/spiderfoot.git
    dest: "{{ spiderfoot_root }}"
    version: "{{ spiderfoot_version }}"
    update: no
  become: yes
  become_user: "{{ spiderfoot_user }}"

- name: Install pip dependencies
  ansible.builtin.pip:
    requirements: "{{ spiderfoot_root }}/requirements.txt"
    virtualenv: "{{ spiderfoot_virtualenv }}"
    virtualenv_python: "{{ python3_bin }}"
  register: pkg_result
  until: pkg_result is success
  become: yes
  become_user: "{{ spiderfoot_user }}"

- name: Ensure .spiderfoot dir exists
  ansible.builtin.file:
    dest: "{{ spiderfoot_home }}/.spiderfoot"
    state: "directory"
    mode: "0700"
    owner: "{{ spiderfoot_user }}"

- name: Set password file
  ansible.builtin.copy:
    content: |
      {{ spiderfoot_web_user }}:{{ spiderfoot_web_pass }}
    dest: "{{ spiderfoot_home }}/.spiderfoot/passwd"
    mode: '0644'
    owner: root
