---

- name: Ensure systemd folder exists
  ansible.builtin.file:
    dest: /etc/systemd/system
    state: directory
    mode: '0755'

- name: Ensure systemd unit files are configured
  ansible.builtin.template:
    src: "systemd-spiderfoot.conf.j2"
    dest: "/etc/systemd/system/spiderfoot.service"
    mode: '0644'
  notify:
    - Reload systemd
    - Restart spiderfoot

- name: Ensure services are enabled and started
  ansible.builtin.service:
    name: spiderfoot
    state: started
    enabled: yes
  when:
    - not is_container | bool
