---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when:
    - not is_container | bool

- name: Restart spiderfoot
  ansible.builtin.service:
    name: spiderfoot
    state: restarted
  when:
    - not is_container | bool
